### ISSUE TITLE
rxPredict using SQL compute context

### ISSUE THREAD

**Issue by svaditya** [bensadeghi/R-demos#3]
I am getting an error while running rxPredict in SQL compute context.
[Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'ccFraudScoreSmall'.
[Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
[Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'ccFraudScoreSmall'.
[Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'ccFraudScoreSmall'.
[Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.

Any idea the reason behind it?

**Comment by bensadeghi** [comment]
Is this still an issue for you?
I can't see why this would occur.
Have you tried the latest version of the script?
